### ISSUE TITLE
FAQ Page formatting

### ISSUE THREAD

**Issue by TptMike** [Everneth/Content#1]
The FAQ page content is currently accurate, however; the formatting between questions is a bit tall. On the Rich Text Editor (or WYSIWYG editor), line breaks (hitting return/enter) are double spaced. In order to get single space line breaks, you have to hold `SHIFT + ENTER`.

Please make the answers single spaced after their corresponding question. The gap between the previous answer and the next question can be double spaced.

**Comment by Ethobling** [comment]
I’ll get on it tonight if all goes according to plan.
